// <auto-generated />
using System;
using HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212105632_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.BaoCaoGiaoDichNgay", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiBaoCao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGiaoDichGui")
                        .HasColumnType("int");

                    b.Property<int>("SoGiaoDichMoSo")
                        .HasColumnType("int");

                    b.Property<int>("SoGiaoDichRut")
                        .HasColumnType("int");

                    b.Property<int>("SoGiaoDichTatToan")
                        .HasColumnType("int");

                    b.Property<int>("TongSoGiaoDich")
                        .HasColumnType("int");

                    b.Property<decimal>("TongSoTienChi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongSoTienThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienRong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("MaNV");

                    b.ToTable("BaoCaoGiaoDichNgay");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.ChiNhanh", b =>
                {
                    b.Property<string>("MaCN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioLamViec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiHD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaCN");

                    b.ToTable("ChiNhanhs");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.GiaoDichNganHang", b =>
                {
                    b.Property<int>("MaGD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGD"));

                    b.Property<string>("LoaiGD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGD")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiGD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaGD");

                    b.HasIndex("MaNV");

                    b.HasIndex("SoTaiKhoan");

                    b.ToTable("GiaoDichNganHang");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.GiaoDichTietKiem", b =>
                {
                    b.Property<int>("MaGD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGD"));

                    b.Property<string>("LoaiGD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaSTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGD")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiGD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaGD");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaSTK");

                    b.ToTable("GiaoDichTietKiem");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.GoiTietKiem", b =>
                {
                    b.Property<int>("MaGoiTietKiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGoiTietKiem"));

                    b.Property<bool>("ChoPhepRutTruocHan")
                        .HasColumnType("bit");

                    b.Property<string>("HinhThucTraLai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KyHanThang")
                        .HasColumnType("int");

                    b.Property<decimal>("LaiSuat")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TaiTucTuDong")
                        .HasColumnType("bit");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaGoiTietKiem");

                    b.ToTable("GoiTietKiems");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.LichHen", b =>
                {
                    b.Property<string>("MaLichHen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChuKH")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KhungGio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichHen");

                    b.HasIndex("MaCN");

                    b.HasIndex("MaDV");

                    b.HasIndex("MaKH");

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.LichSuDangNhap", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("DiaChiIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LoaiNguoiDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaDN")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLanDangNhapThatBai")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGDangNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TGDangXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDN");

                    b.ToTable("LichSuDangNhaps");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.LoaiDichVu", b =>
                {
                    b.Property<string>("MaDV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ChoPhepDatLich")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThoiGianUocTinh")
                        .HasColumnType("int");

                    b.HasKey("MaDV");

                    b.ToTable("LoaiDichVus");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.OTPVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OTPVerifications");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.SoTietKiem", b =>
                {
                    b.Property<int>("MaSTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSTK"));

                    b.Property<int>("KyHan")
                        .HasColumnType("int");

                    b.Property<double>("LaiSuat")
                        .HasColumnType("float");

                    b.Property<string>("LoaiTaiTuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayDaoHan")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("DATEADD(MONTH, [KyHan], [NgayMoSo])");

                    b.Property<DateTime>("NgayMoSo")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<decimal>("SoTienGui")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSTK");

                    b.HasIndex("SoTaiKhoan");

                    b.ToTable("SoTietKiem");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.TaiKhoanNganHang", b =>
                {
                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayMoTaiKhoan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoDu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SoTaiKhoan");

                    b.HasIndex("MaKH");

                    b.ToTable("TaiKhoanNganHang");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaKH");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigitalPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPinSetup")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.BaoCaoGiaoDichNgay", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.GiaoDichNganHang", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", "NhanVien")
                        .WithMany("GiaoDichNganHangs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.TaiKhoanNganHang", "TaiKhoanNganHang")
                        .WithMany("GiaoDichNganHangs")
                        .HasForeignKey("SoTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("TaiKhoanNganHang");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.GiaoDichTietKiem", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", "NhanVien")
                        .WithMany("GiaoDichTietKiems")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.SoTietKiem", "SoTietKiem")
                        .WithMany("GiaoDichTietKiems")
                        .HasForeignKey("MaSTK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NhanVien");

                    b.Navigation("SoTietKiem");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.LichHen", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaCN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.LoaiDichVu", "LoaiDichVu")
                        .WithMany()
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiDichVu");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.LichSuDangNhap", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaDN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.SoTietKiem", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.TaiKhoanNganHang", "TaiKhoanNganHang")
                        .WithMany("SoTietKiems")
                        .HasForeignKey("SoTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoanNganHang");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.TaiKhoanNganHang", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", "KhachHang")
                        .WithMany("TaiKhoanNganHangs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.ThongBao", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", "KhachHang")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.SoTietKiem", b =>
                {
                    b.Navigation("GiaoDichTietKiems");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.TaiKhoanNganHang", b =>
                {
                    b.Navigation("GiaoDichNganHangs");

                    b.Navigation("SoTietKiems");
                });

            modelBuilder.Entity("HeThongGuiRutTienTietKiemTheoNghiepVuNganHang.Models.User", b =>
                {
                    b.Navigation("GiaoDichNganHangs");

                    b.Navigation("GiaoDichTietKiems");

                    b.Navigation("TaiKhoanNganHangs");

                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
